#!/usr/bin/env python3
import hashlib,json,os,zipfile
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; REPO=ROOT.parents[1]; BUILD=ROOT/"build"; P=BUILD/"promotion"; P.mkdir(parents=True,exist_ok=True)
prod=["public-components/runtime-contracts/src/main/java/io/toolbox/contracts/runtime/Contracts.java","public-components/runtime-contracts/src/main/java/io/toolbox/contracts/runtime/ProductRegistry.java","public-components/runtime-safety-contracts/src/main/java/io/toolbox/contracts/safety/SafetyContracts.java","public-components/runtime-safety-contracts/src/main/java/io/toolbox/contracts/safety/DiagnosticBuffer.java","public-components/runtime-safety-contracts/src/main/java/io/toolbox/contracts/safety/ResourceGuard.java","public-components/runtime-safety-contracts/src/main/java/io/toolbox/contracts/safety/RecoveryMachine.java","public-components/stage-a-foundation/src/main/java/io/toolbox/stagea/StageAContracts.java","public-components/stage-a-foundation/src/main/java/io/toolbox/stagea/ExecutionGuard.java","public-components/stage-a-foundation/src/main/java/io/toolbox/stagea/DiagnosticMapper.java","public-components/stage-a-foundation/src/main/java/io/toolbox/stagea/RecoveryCoordinator.java","public-components/stage-a-foundation/src/main/java/io/toolbox/stagea/SafeUiPolicy.java","public-components/stage-a-foundation/src/main/java/io/toolbox/stagea/SafeUiActionPolicy.java","public-components/stage-a-foundation/src/main/java/io/toolbox/stagea/HealthAggregator.java"]
prod += [p.relative_to(REPO).as_posix() for p in sorted((REPO/"public-components/stage-a-android-host/src/main/java/io/toolbox/stagea/android").glob("*.java"))]; assert len(prod)==22
meta=["public-components/stage-a-foundation/COMPONENT_SPEC.json","public-components/stage-a-foundation/CONTRACT.json","public-components/stage-a-foundation/ASSURANCE_PLAN_R1_R9.json","public-components/stage-a-foundation/PRIVATE_INTEGRATION_REQUIREMENTS.json","public-components/stage-a-android-host/COMPONENT_SPEC.json","public-components/stage-a-android-host/CONTRACT.json","public-components/stage-a-android-host/ASSURANCE_PLAN_R1_R9.json","public-components/stage-a-android-host/PRIVATE_INTEGRATION_REQUIREMENTS.json"]
ev=["public-components/stage-a-foundation/build/assurance/prebuild-evidence.json","public-components/stage-a-foundation/build/assurance/mutation-evidence.json","public-components/stage-a-foundation/build/assurance/r1-r9-stage-a-evidence.json","public-components/stage-a-foundation/build/test-summary.txt","public-components/stage-a-android-host/build/assurance/android-host-prebuild-evidence.json","public-components/stage-a-android-host/build/assurance/android-host-mutation-evidence.json","public-components/stage-a-android-host/build/assurance/android-host-r1-r9-evidence.json","public-components/stage-a-android-host/build/host-runtime-summary.txt","public-components/stage-a-android-host/build/jvm/output.txt"]
for rel in prod+meta+ev: assert (REPO/rel).is_file(),rel
for rel in prod: assert "Simulator.java" not in rel and "HostTestActivity.java" not in rel and "/src/test/" not in rel
stage_e=json.loads((REPO/"public-components/stage-a-foundation/build/assurance/r1-r9-stage-a-evidence.json").read_text()); host_e=json.loads((REPO/"public-components/stage-a-android-host/build/assurance/android-host-r1-r9-evidence.json").read_text())
assert stage_e["status"]=="PASS" and stage_e["crossDomain"]["sharedProductRegistryIdentity"]=="PASS" and stage_e["androidHost"]["sharedProductRegistry"]=="PASS" and stage_e["androidHost"]["safeUiActions"]=="PASS"
assert host_e["status"]=="PASS" and host_e["evidence"]["sharedProductRegistry"]=="PASS" and host_e["evidence"]["safeUiActions"]=="PASS"
def sha(p): return hashlib.sha256(p.read_bytes()).hexdigest()
src_hash={r:sha(REPO/r) for r in prod}; meta_hash={r:sha(REPO/r) for r in meta}; ev_hash={r:sha(REPO/r) for r in ev}
sz=P/"toolbox-stage-a-1.1.0-production-sources.zip"
with zipfile.ZipFile(sz,"w",compression=zipfile.ZIP_DEFLATED) as z:
  for rel in prod:
    i=zipfile.ZipInfo(rel); i.date_time=(1980,1,1,0,0,0); i.compress_type=zipfile.ZIP_DEFLATED; i.external_attr=0o100644<<16; z.writestr(i,(REPO/rel).read_bytes())
jar=BUILD/"package/toolbox-stage-a-foundation-0.1.0.jar"; assert jar.is_file()
m={"schemaVersion":2,"projectId":"ToolBox","stageId":"A","stageVersion":"1.1.0","status":"STAGE_A_READY_PRIVATE","sourceRepository":os.environ.get("GITHUB_REPOSITORY","LOCAL_PUBLIC_VALIDATION"),"sourceCommitSha":os.environ.get("GITHUB_SHA","LOCAL_PUBLIC_VALIDATION"),"workflowRunId":os.environ.get("GITHUB_RUN_ID","LOCAL_PUBLIC_VALIDATION"),"promotionBoundary":"STAGE_ONLY","substeps":["A1","A2","A3","A4"],"substepsArePrivateBoundaries":False,"componentReadyPrivateAuthorizesPrivateStageIntegration":False,"privateImplementationRequired":False,"privateWiringOnly":True,"dependencies":[{"componentId":"public.runtime-contracts","componentVersion":"0.1.0","contractVersion":"1.0.0"},{"componentId":"public.runtime-safety-contracts","componentVersion":"0.1.0","contractVersion":"1.0.0"},{"componentId":"public.stage-a-foundation","componentVersion":"0.2.0","contractVersion":"1.1.0"},{"componentId":"public.stage-a-android-host","componentVersion":"0.1.0","contractVersion":"1.0.0"}],"productionSourceArchive":{"path":sz.name,"sha256":sha(sz),"size":sz.stat().st_size,"sourceCount":len(prod),"sourceHashes":src_hash,"simulatorSourceIncluded":False,"testSourceIncluded":False,"androidTestHarnessIncluded":False,"promotionAllowed":True},"verificationJar":{"path":jar.name,"sha256":sha(jar),"size":jar.stat().st_size,"privateProductionUseAllowed":False},"metadataHashes":meta_hash,"evidenceHashes":ev_hash,"assurance":{"r1ToR9PublicStageClosure":"PASS","registryIntegrationSimulator":"PASS","androidHostApi30Runtime":"PASS","androidHostProcessRestartDurability":"PASS","androidHostSharedProductRegistry":"PASS","androidHostCorruptionRejection":"PASS","androidHostSafeUiRender":"PASS","androidHostSafeUiActions":"PASS","mutationChallenge":"PASS","unknown":0,"skipped":0,"staleEvidence":0,"finalApplicationSafe100Claimed":False},"publicBoundaries":{"privateContentIncluded":False,"privateReadAccess":False,"privateExecutionThroughPublic":False,"publicAndroidHostRuntimeTested":True,"publicAndroidHostRuntimeApi":30,"publicAndroidHostWitnessAbi":"x86_64","finalAndroid11Arm64RuntimeClaimed":False,"firebaseUsed":False}}
mp=P/"stage-a-promotion-manifest.json"; mp.write_text(json.dumps(m,indent=2,sort_keys=True)+"\n"); bundle=P/"toolbox-stage-a-ready-private.zip"
with zipfile.ZipFile(bundle,"w",compression=zipfile.ZIP_DEFLATED) as z:
  for path in [sz,mp]+[REPO/r for r in meta+ev]:
    arc=path.name if path in {sz,mp} else path.relative_to(REPO).as_posix(); i=zipfile.ZipInfo(arc); i.date_time=(1980,1,1,0,0,0); i.compress_type=zipfile.ZIP_DEFLATED; i.external_attr=0o100644<<16; z.writestr(i,path.read_bytes())
(P/"artifact-digests.json").write_text(json.dumps({"schemaVersion":2,"stageAReadyPrivateZip":{"sha256":sha(bundle),"size":bundle.stat().st_size},"productionSourceZip":{"sha256":sha(sz),"size":sz.stat().st_size},"manifest":{"sha256":sha(mp),"size":mp.stat().st_size}},indent=2,sort_keys=True)+"\n"); print("STAGE_A_PACKAGE_VALIDATION = PASS"); print("STAGE_A_STATUS=STAGE_A_READY_PRIVATE"); print("SHARED_PRODUCT_REGISTRY=PASS"); print(f"PRODUCTION_SOURCE_COUNT={len(prod)}"); print(f"STAGE_A_BUNDLE_SHA256={sha(bundle)}")
