plugins {
    id 'com.android.application'
}

android {
    namespace 'com.toolbox.tools'
    compileSdk 30

    defaultConfig {
        applicationId 'com.toolbox.tools'
        minSdk 30
        targetSdk 30
        versionCode 11
        versionName '11.0-tahap11-dev'
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
    }

    lint {
        disable 'ExpiredTargetSdkVersion'
    }
}

dependencies {
    testImplementation 'junit:junit:4.13.2'
}
