package com.toolbox.tools.runtime;

public enum DiagnosticCode {
    BROKEN_REFERENCE,
    BROKEN_DATA_REFERENCE,
    BROKEN_NAVIGATION_REFERENCE,
    COMPONENT_UNAVAILABLE,
    ACTION_IMPLEMENTATION_MISSING,
    CONTRACT_MISMATCH,
    BINDING_AMBIGUOUS,
    BINDING_CYCLE_SUPPRESSED,
    FLOW_LIMIT_EXCEEDED,
    MISSING_ASSET,
    PERMISSION_CONTRACT_MISSING,
    LAYOUT_CONSTRAINT_CONFLICT,
    STALE_WRITE,
    CAPABILITY_INCOMPATIBLE,
    SIGNING_IDENTITY_MISMATCH
}
